package com.dynamsoft.dwt.common;

/// CAP_PRINTER values.
public interface EnumDWT_CapPrinter{
  int TWPR_IMPRINTERTOPBEFORE = 0;
  int TWPR_IMPRINTERTOPAFTER = 1;
  int TWPR_IMPRINTERBOTTOMBEFORE = 2;
  int TWPR_IMPRINTERBOTTOMAFTER = 3;
  int TWPR_ENDORSERTOPBEFORE = 4;
  int TWPR_ENDORSERTOPAFTER = 5;
  int TWPR_ENDORSERBOTTOMBEFORE = 6;
  int TWPR_ENDORSERBOTTOMAFTER = 7;
}